### ISSUE TITLE
Add installaton of AdoptOpenJDK and JRE pre-requisite

### ISSUE THREAD

**Issue by beutepa** [sdl/ISHServer#48]
Add installation of AdoptOpenJDK and JRE pre-requisite

**Comment by ddemeyer** [comment]
I like this @beutepa ... technically however I think we should continue to distinguish JRE and JDK. The ZIP file you are adding contains `JRE` in the name but your variable is `ISHServer:AdoptOpenJDK`. So suggesting a `ISHServer:AdoptOpenJRE` next to the `ISHServer:AdoptOpenJDK` (and existing values `JRE` and `JDK`) as you can see in the platform dropdown on https://adoptopenjdk.net/installation.html
